### ISSUE TITLE
Not working in Nested components

### ISSUE THREAD

**Issue by ranavc32** [mseemann/angular-mdl-a4-angular-cli#2]
Hi mseemann , 
I testing this application , when we are creating a new component say `header` and putting the ` mdl-layout-header` in its template  and then use <app-header></app-header> in `appcomponent` , Header is not rendering.
Do we need to make some additional imports in `headercomponent.ts` file ?

**Comment by mseemann** [comment]
i think here is the answer http://stackoverflow.com/questions/39550175/angular2-mdl-break-layout-in-components-does-not-work :)

**Comment by ranavc32** [comment]
Yes, I got it. Thank you for creating such awesome package.
